[package]
name = "mpeg2ts-reader-shootout"
version = "0.0.1"
publish = false
edition = "2021"

[dependencies]
mpeg2ts = "0.1.1"
mpeg2ts-reader = { path = ".." }
ffmpeg-sys-next = { version = "8.1.0", default-features = false, features = ["avcodec", "avformat"] }

[dev-dependencies]
criterion = "0.8"

[[bench]]
name = "bench"
harness = false
